#!/usr/bin/env node
// tools/apertures.mjs — THE OPENINGS, INVENTORIED.
//
//   node tools/apertures.mjs            -> docs/APERTURES.md
//   node tools/apertures.mjs --check    CI: fail if it is out of date
//
// "i think i need to think about it in terms of intersections, where are the
//  openings, how big are they, etc."
//
// Everything here is measured off the whole grammar, not asserted.  See
// js/aperture.js for what it found and why it makes the system small.

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { everyBlock } from '../js/enumerate.js';
import { measure, joinery, planMask, keyOf, profile, turnMask } from '../js/measure.js';
import { blockFromRecipe } from '../js/stack.js';
import { PLANS, PLAN_IDS } from '../js/plan.js';
import { SUB, SUB_YARDS, BLOCK_YARDS } from '../js/cube.js';
import { WORDS, ODD_WORDS, wordOf, wordsOfWall, openings, describeWall, wordsByPlan } from '../js/aperture.js';

const argv = process.argv.slice(2);
const arg = (n, d) => { const i = argv.indexOf(n); return i >= 0 && argv[i + 1] ? argv[i + 1] : d; };
const has = (n) => argv.includes(n);
const out = resolve(arg('--out', 'docs/APERTURES.md'));

const sheets = everyBlock().recipes.map((r) => measure(r, blockFromRecipe(r))).filter(Boolean);
const serve = joinery(sheets);

/* --------------------------------------------------------------- tallies */

const wordCount = new Map();
const wallKeys = new Set();
const triples = new Set();
const oddBlocks = new Set();
const size = { width: new Map(), height: new Map(), sill: new Map(), kind: new Map(), per: new Map() };
const bump = (m, k, n = 1) => m.set(k, (m.get(k) || 0) + n);

for (const side of ['-x', '+x', '-y', '+y']) {
  for (const [key, set] of serve.get(side)) {
    const n = set.size;
    wallKeys.add(key);
    const words = wordsOfWall(key);
    triples.add(words.join('|'));
    for (const w of words) {
      bump(wordCount, w, n);
      if (ODD_WORDS.includes(w)) for (const r of set) oddBlocks.add(r);
    }
    const O = openings(key);
    bump(size.per, O.length, n);
    for (const o of O) {
      bump(size.width, o.width, n);
      bump(size.height, o.height, n);
      bump(size.sill, o.sill, n);
      bump(size.kind, o.kind, n);
    }
  }
}

const totalWords = [...wordCount.values()].reduce((a, b) => a + b, 0);
const planTable = wordsByPlan(planMask, PLAN_IDS, PLANS);
const soleMakers = new Map();
for (const [bits, ids] of planTable) if (ids.size === 1) soleMakers.set(bits, [...ids][0]);

/* ---------------------------------------------------------------- report */

const L = [];
const p = (s = '') => L.push(s);
const pct = (v, t) => `${(100 * v / t).toFixed(1)}%`;
const share = (m) => {
  const t = [...m.values()].reduce((a, b) => a + b, 0);
  return [...m.entries()].sort((a, b) => b[1] - a[1]).map(([k, v]) => [k, v, pct(v, t)]);
};

p('# The openings');
p('');
p('Generated by `node tools/apertures.mjs`. **Do not edit by hand.**');
p('');
p('> *"i think i need to think about it in terms of intersections, where are the');
p('> openings, how big are they, etc."*');
p('');
p('Measured across every wall the grammar can present — all');
p(`${totalWords.toLocaleString()} storey-faces of ${wallKeys.size.toLocaleString()} distinct walls. The answer is much smaller`);
p('than the block count suggests.');
p('');

p('## The vertical is already solved');
p('');
p('A block is three plans extruded, so **every opening in the grammar is a');
p('rectangle whose height is 3, 6 or 9 yards and whose sill sits at 0, 3 or 6.**');
p('There is no design freedom in the vertical at all — an opening occupies one');
p('storey, two, or all three.');
p('');
p('| | 3 yd | 6 yd | 9 yd | other |');
p('|---|---:|---:|---:|---:|');
const hh = new Map(share(size.height).map(([k, v]) => [k, v]));
const ss = new Map(share(size.sill).map(([k, v]) => [k, v]));
const tot = [...size.height.values()].reduce((a, b) => a + b, 0);
p(`| **height** | ${pct(hh.get(3) || 0, tot)} | ${pct(hh.get(6) || 0, tot)} | ${pct(hh.get(9) || 0, tot)} | ${pct(tot - (hh.get(3) || 0) - (hh.get(6) || 0) - (hh.get(9) || 0), tot)} |`);
p(`| **sill at** | ${pct(ss.get(3) || 0, tot)} | ${pct(ss.get(6) || 0, tot)} | — | ${pct(ss.get(0) || 0, tot)} at 0 |`);
p('');
p('The "other" in both rows is the arches, and only the arches — the vault curve');
p('is the one thing in the game that does not land on a storey.');
p('');

p('## So the only real variable is the WORD');
p('');
p('One storey of one wall, nine yards across. Of the **512** possible nine-bit');
p(`words the whole grammar uses **${wordCount.size}**, and three of those are vestigial:`);
p(`they occur only in the ${oddBlocks.size} arches and account for`);
p(`${ODD_WORDS.reduce((n, w) => n + (wordCount.get(w) || 0), 0)} storey-faces out of ${totalWords.toLocaleString()}.`);
p('');
p('```');
p('  a wall  =  three storeys, each one of TEN words');
p('```');
p('');
p(`${triples.size.toLocaleString()} of the 2,197 possible word-triples actually occur, so in practice you may`);
p('pick a word per storey and the block usually exists.');
p('');

p('## The ten words');
p('');
p('Drawn across the nine yards of the face, `#` stone and `.` opening. Two blocks');
p('meet flush when their facing walls are **identical word for word** — not');
p('mirrored. Rotation is free at placement, which is why the handed pairs below');
p('carry exactly equal counts: a block offering `return-l` can be turned to offer');
p('`return-r`.');
p('');
p('| word | | share | what it is | only plan that makes it |');
p('|---|---|---:|---|---|');
for (const w of WORDS) {
  const n = wordCount.get(w.bits) || 0;
  const art = [...w.bits].map((c) => (c === '1' ? '#' : '.')).join('');
  const sole = soleMakers.get(w.bits);
  p(`| \`${w.name}\` | \`${art}\` | ${pct(n, totalWords)} | ${w.gloss} | ${sole ? `**\`${sole}\`**` : '—'} |`);
}
p('');

p('### Three plans are the sole source of their word');
p('');
p('That makes them structurally fragile: a storey built from one can only ever');
p('meet a storey built from the same one.');
p('');
for (const [bits, id] of soleMakers) {
  if (!WORDS.some((w) => w.bits === bits)) continue;
  p(`- **\`${id}\`** is the only maker of \`${wordOf(bits).name}\``);
}
p('');
p('');
p('**And it is expensive.** Grouping every block by whether it presents a');
p('sole-source word on any wall, and measuring how many of the 10,826 can meet');
p('its walls:');
p('');
p('| presents | blocks | mean reach | |');
p('|---|---:|---:|---|');
{
  const sole = {};
  for (const [bits, id] of soleMakers) if (WORDS.some((w) => w.bits === bits)) sole[bits] = id;
  const groups = new Map();
  for (const s of sheets) {
    let k = 'nothing sole-source';
    for (const side of ['-x', '+x', '-y', '+y']) {
      for (const w of wordsOfWall(keyOf(profile(s.mask, side)))) if (sole[w]) { k = sole[w]; break; }
      if (k !== 'nothing sole-source') break;
    }
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k).push(s);
  }
  const base = groups.get('nothing sole-source');
  const baseReach = base.reduce((n, s) => n + s.reach, 0) / base.length;
  for (const [k, v] of [...groups.entries()].sort((a, b) => b[1].length - a[1].length)) {
    const r = v.reduce((n, s) => n + s.reach, 0) / v.length;
    const note = k === 'nothing sole-source' ? 'the baseline' : `**${(baseReach / r).toFixed(1)}× worse**`;
    p(`| ${k === 'nothing sole-source' ? k : `a word only \`${k}\` makes`} | ${v.length.toLocaleString()} | ${r.toFixed(0)} | ${note} |`);
  }
}
p('');
p('So a block showing `chamfer` anywhere can meet **29** of the 10,826 instead of');
p('239. Nearly half the grammar carries one of these words on some wall. **A');
p('second plan emitting `chamfer` would multiply the reach of 992 blocks by');
p('eight** — and it need not resemble `rounded` at all, it only has to leave');
p('stone in the same nine yards.');
p('');
p('This is the mechanism behind the census\'s one dead end. `S:rounded,rounded,');
p('rounded` presents `chamfer` on all three storeys of all four walls, `rounded`');
p('is the only plan that makes `chamfer`, and `rounded` is four-fold symmetric so');
p('there is exactly one such block. **It can only ever meet itself, and there is');
p('no second one.** Not a quirk of that block — a property of the word.');
p('');

p('## Which plan emits which word');
p('');
p('The table to design against, because a plan\'s word is what decides who its');
p('blocks can ever meet.');
p('');
p('| word | plans |');
p('|---|---|');
for (const w of WORDS) {
  const ids = planTable.get(w.bits);
  p(`| \`${w.name}\` | ${ids ? [...ids].sort().map((i) => `\`${i}\``).join(', ') : '— *(arches only)*'} |`);
}
p('');

p('## How big are the openings');
p('');
p(`One sub-block is ${SUB_YARDS} yard; a block is ${BLOCK_YARDS} yards across.`);
p('');
p('| width | share | | openings on a wall | share |');
p('|---:|---:|---|---:|---:|');
{
  const w = share(size.width), per = share(size.per);
  for (let i = 0; i < Math.max(w.length, per.length); i++) {
    const a = w[i] ? `| ${w[i][0]} yd | ${w[i][2]} |` : '| | |';
    const b = per[i] ? `| ${per[i][0]} | ${per[i][2]} |` : '| | |';
    p(`${a} ${b}`);
  }
}
p('');
p('**Three yards is the doorway** — 46% of every opening in the game — and nine');
p('yards, the whole face, is next at 28%. Between them they are three quarters of');
p('all openings, which is why the vocabulary coheres at all.');
p('');
p('| kind | share | |');
p('|---|---:|---|');
for (const [k, , s] of share(size.kind)) {
  const gloss = { door: 'sill on the floor — you walk through it', loggia: 'open to the ceiling', slot: 'floor to ceiling, the full nine yards', window: 'masonry above and below' }[k];
  p(`| ${k} | ${s} | ${gloss} |`);
}
p('');

p('## Reading a block');
p('');
p('Any block\'s wall, in this language:');
p('');
p('| block | its `+x` wall, bottom storey first |');
p('|---|---|');
for (const r of ['S:full,full,full:stone', 'S:full,bar,full:stone', 'S:ell,ell,ell:stone', 'S:twin,twin,twin:stone', 'S:drum,drum,drum:stone', 'S:rounded,rounded,rounded:stone']) {
  const sh = sheets.find((s) => s.recipe === r);
  if (sh) p(`| \`${r}\` | ${describeWall(keyOf(profile(sh.mask, '+x')))} |`);
}
p('');
void turnMask;

const text = L.join('\n') + '\n';

if (has('--check')) {
  const now = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (now !== text) { console.error(`${out} is out of date — run: node tools/apertures.mjs`); process.exit(1); }
  console.log(`${out}  up to date`);
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, text);
  console.log(`${out}`);
  console.log(`  ${wordCount.size} distinct edge words of 512 possible; ${WORDS.length} carry the grammar`);
  console.log(`  ${triples.size.toLocaleString()} word-triples of 2,197 · ${wallKeys.size.toLocaleString()} distinct walls`);
  console.log(`  sole-source words: ${[...soleMakers.entries()].filter(([b]) => WORDS.some((w) => w.bits === b)).map(([b, i]) => `${i}→${wordOf(b).name}`).join(', ')}`);
}
