#!/usr/bin/env node
// tools/blockdump.mjs — WRITE THE HAND DOWN.
//
// A block's identity is its recipe (see js/recipe.js), and a recipe is a short
// string.  So the whole catalogue can be archived as text, read by a human,
// diffed between sessions, and pasted back in.  That is the answer to "are you
// saving the blocks you are creating anywhere?" — they were reproducible from a
// seed but nothing was written down, and a seed is only reproducible until the
// generator changes underneath it.
//
//   node tools/blockdump.mjs                    the default hand -> docs/BLOCKS.md
//   node tools/blockdump.mjs --n 48 --seed 7
//   node tools/blockdump.mjs --check            fail if the file is out of date
//
// `--check` is the one CI runs.  If the generator changes what the default hand
// deals, this file changes, and the diff says exactly which blocks moved — so a
// re-deal is something you SEE in a commit rather than something that happens
// to you.

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { buildCatalog } from '../js/stack.js';
import { decode } from '../js/recipe.js';
import { SUB, BLOCK_YARDS } from '../js/cube.js';

const argv = process.argv.slice(2);
const arg = (n, d) => { const i = argv.indexOf(n); return i >= 0 && argv[i + 1] ? argv[i + 1] : d; };
const has = (n) => argv.includes(n);

const N = Number(arg('--n', '24'));
const SEED = Number(arg('--seed', '1'));
const out = resolve(arg('--out', 'docs/BLOCKS.md'));

const cat = buildCatalog(N, SEED);

const rows = [...cat.values()].map((d) => {
  const anchors = d.anchors.map((a) => `${a.side}@${a.u},${a.z}`).join(' ');
  return { recipe: d.recipe, family: d.family, faces: d.mesh.faces.length, anchors };
});

const lines = [];
lines.push('# The hand');
lines.push('');
lines.push('Generated by `node tools/blockdump.mjs`. **Do not edit by hand** — but do');
lines.push('read the diff when it changes, because a change here means every building');
lines.push('that was built from this shelf is now offered a different shelf.');
lines.push('');
lines.push('A block\'s identity is its **recipe**, and a save writes the recipes it uses');
lines.push('into its own palette, so a saved building cannot be re-dealt by anything that');
lines.push('happens here. See `js/recipe.js`.');
lines.push('');
lines.push(`\`buildCatalog(${N}, ${SEED})\` · a block is ${BLOCK_YARDS} yards cubed · ${SUB}×${SUB}×${SUB} sub-blocks`);
lines.push('');
lines.push('| recipe | family | faces | anchor sites |');
lines.push('|---|---|---:|---|');
for (const r of rows) {
  lines.push(`| \`${r.recipe}\` | ${r.family} | ${r.faces} | ${r.anchors || '—'} |`);
}
lines.push('');
lines.push('## The grammar');
lines.push('');
lines.push('```');
lines.push('S:<plan>,<plan>,<plan>:<material>      a stack, one plan per third');
lines.push('A:<axis><hand>:<plan>:<material>       an arch: piers, then the vault');
lines.push('<plan>/<q>                             quarter-turned q times');
lines.push('hand: + both spandrels · l left · r right');
lines.push('```');
lines.push('');
lines.push('A plan may be **added** freely: no existing recipe mentions it, so no existing');
lines.push('block changes. A plan may **not** be renamed or removed without breaking every');
lines.push('recipe that names it — `decode` reports those rather than substituting.');
lines.push('');
const text = lines.join('\n') + '\n';

// Every recipe must round-trip, or the archive is a list of things that cannot
// be rebuilt from it.
for (const r of rows) {
  const d = decode(r.recipe);
  if (!d.ok) { console.error(`UNBUILDABLE: ${r.recipe} — ${d.why}`); process.exit(1); }
}

if (has('--check')) {
  const now = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (now !== text) {
    console.error(`${out} is out of date — run: node tools/blockdump.mjs`);
    process.exit(1);
  }
  console.log(`${out}  up to date  (${rows.length} blocks)`);
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, text);
  console.log(`${out}  ${rows.length} blocks, ${rows.filter((r) => r.anchors).length} with anchor sites`);
}
